### ISSUE TITLE
API to annotate 3D models on sketchfab

### ISSUE THREAD

**Issue by addy1997** [sketchfab/viewer-api#8]
Hi @arthurjamain,

What API is used to add labels/annotations to the 3D model on Sketchfab? This 3D model for instance 
![image](https://github.com/sketchfab/viewer-api/assets/29406906/491b160c-760e-4658-a891-674fe68d56c3)

Some parts of this model (labelled 1, 2, and 3)

Thanks,
Adwait

**Comment by PadreZippo** [comment]
There is currently no way to create/edit annotations in the Data API. Those would be "permanent" annotations as if you created them in 3D Settings:

https://help.sketchfab.com/hc/en-us/articles/202512456-Annotations

However, the Viewer API does let you create and edit annotations at runtime, so you can add them to an instance of the viewer, but not "save" them permanently to the model on Sketchfab:

- https://sketchfab.com/developers/viewer/functions#api-section-annotations
- https://jsfiddle.net/PadreZippo/u2yhtj1L/
- https://jsfiddle.net/PadreZippo/zxowd8t1/

**Comment by addy1997** [comment]
Hi @PadreZippo,

Thanks for getting back so quickly. Actually, I am trying to create annotations for [my model](https://jsfiddle.net/adwait3301/adxg1pfm). I am using AFRAME to visualize the models in VR. Can I use Sketchfab API to annotate and label the models?

**Comment by PadreZippo** [comment]
Hi,

Sorry I'm a bit confused by the link you shared, as it seems to not be using Sketchfab at all. If you want to use Sketchfab to add annotations to models, you will need to upload a model to Sketchfab and embed it in your site / application.

**Comment by addy1997** [comment]
@PadreZippo, what I meant is that can I use the sketchfab API with [AFRAME](https://github.com/aframevr/aframe) for my custom models?

**Comment by PadreZippo** [comment]
You can only use the Sketchfab API with Sketchfab models in the Sketchfab viewer. So unless you're embedding a Sketchfab iframe, the API is not relevant.
